version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_db:/data/db

  # Node API service
  api:
    build: "./server/"
    ports:
      - 7212:7212
    environment:
      MONGO_DB: mongodb://mongo_db:27017/ictc
    depends_on:
      - mongo_db

  client:
    build: "./client/main_page/"
    ports:
      - 7211:7211

volumes:
  mongo_db: {}
